name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Restore gradle global directory
        uses: actions/cache/restore@v4
        id: cache
        with:
          path: |
              ~/.gradle/
              .gradle/
          key: global-gradle-
          restore-keys: global-gradle-

      - name: set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Gradle
        run: ./gradlew build
        
